package backend

const (
	PLATFORM_GOOGLE                = "googleAds"
	PLATFORM_FACEBOOK              = "facebookMarketing"
	PLATFORN_TIKTIK_MARKETING      = "tiktokMarketing"
	PLATFORN_SNAPCHAT_MARKETING    = "snapchatMarketing"
	PLATFORN_SNAPCHAT_PINTEREST    = "pinterest"
	PLATFORN_SNAPCHAT_APPLOVIN     = "applovin"
	PLATFORN_SNAPCHAT_BINGADS      = "bingAds"
	PLATFORN_SNAPCHAT_AMAZONVENDOR = "amazonVendorPartner"
	PLATFORN_SNAPCHAT_FAIRING      = "fairing"

	ADS_PLATFORM_GOOGLE    = "Google"
	ADS_PLATFORM_FACEBOOK  = "Meta"
	ADS_PLATFORM_TIKTOK    = "TikTok"
	ADS_PLATFORM_SNAPCHAT  = "Snapchat"
	ADS_PLATFORM_PINTEREST = "Pinterest"
	ADS_PLATFORM_APPLOVIN  = "Applovin"
	ADS_PLATFORM_BINGADS   = "Microsoft"
)

var PlatformMap = map[string]string{
	PLATFORM_GOOGLE:             ADS_PLATFORM_GOOGLE,
	PLATFORM_FACEBOOK:           ADS_PLATFORM_FACEBOOK,
	PLATFORN_TIKTIK_MARKETING:   ADS_PLATFORM_TIKTOK,
	PLATFORN_SNAPCHAT_MARKETING: ADS_PLATFORM_SNAPCHAT,
	PLATFORN_SNAPCHAT_PINTEREST: ADS_PLATFORM_PINTEREST,
	PLATFORN_SNAPCHAT_APPLOVIN:  ADS_PLATFORM_APPLOVIN,
	PLATFORN_SNAPCHAT_BINGADS:   ADS_PLATFORM_BINGADS,
}

// IsWmOnlyPlatform 检查是否为仅WM数据的平台类型
func IsWmOnlyPlatform(platform string) bool {
	return platform == PLATFORN_SNAPCHAT_AMAZONVENDOR ||
		platform == PLATFORN_SNAPCHAT_FAIRING
}
